
presentation.html: presentation.rst Makefile
	python rst-directive.py \
		--stylesheet=pygments.css \
		--theme=small-white \
		presentation.rst presentation.html	
	# rst2s5.bat --theme small-white presentation.rst presentation.html

